# Generated by Django 5.0.7 on 2024-08-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('items_count', models.IntegerField()),
                ('attributes', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Varient',
        ),
        migrations.AddField(
            model_name='category',
            name='product_attributes_schema',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='variant_attributes_schema',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
