# Generated by Django 5.0.7 on 2024-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_attributes_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='variant_attributes_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
